let shopItemsData = [
    {
      id: "Tomatoes",
      name: "Tomatoes",
      price: 5,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "./tomatoes.jpg",
    },
    {
      id: "carrot",
      name: "Carrot",
      price: 10,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "./carrot.jpg",
    },
    {
      id: "Onions",
      name: "Onions",
      price: 15,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
    {
      id: "Brinjal",
      name: "Brinjal",
      price: 30,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg32.jpeg",
    },
    {
      id: "carrot",
      name: "carrot",
      price: 30,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "./carrot.jpg",
    },
    {
      id: "apple",
      name: "apple",
      price: 23,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "./apples.jpg",
    },
    {
      id: "banana",
      name: "banana",
      price: 30,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "./Bananas.jpg",
    },
    {
      id: "Dal",
      name: "Dal",
      price: 15,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
    {
      id: "Rice",
      name: "Rice",
      price: 30,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
    {
      id: "Chana",
      name: "Chana",
      price: 25,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
    {
      id: "Dry Grapes",
      name: "Dry Grapes",
      price: 25,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
    {
      id: "Cashew",
      name: "Cashew",
      price: 25,
      desc: "The quantity Product from Chandan pvt ltd. 100% Natural & 100% HEALTHY !!...",
      img: "images\veg33.jpeg",
    },
  ];